[workspace]
authors = ["Matthew McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
name = "cmake-w3-externaldata-upload"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
