[workspace]
authors = ["Matthew McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
name = "cmake-w3-externaldata-upload"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pnpm-install = { cmd="pnpm install", description="Install JavaScript dependencies", outputs=["node_modules/.pnpm-workspace-state.json"] }
build = { cmd="pnpm build", description="Build JavaScript code", depends-on=["pnpm-install"], outputs=["dist"] }
start-hypha = { cmd="pnpm start-hypha", description="Start the Hypha server", depends-on=["build"] }
start = { cmd="pnpm start", description="Start the application", depends-on=["build"] }
start-hypha-service = { cmd="pnpm start-hypha-service", description="Start the production Hypha service", depends-on=["build"] }
preview = { cmd="pnpm preview", description="Preview the production web page", depends-on=["build"] }

[dependencies]
python = "3.11.*"
pnpm = ">=10.10.0,<11"
pandas = ">=2.2.3,<3"

[pypi-dependencies]
duckdb = ">=1.2.2, <2"
mailjet-rest = ">=1.4.0, <2"
python-dotenv = ">=1.1.0, <2"
hypha = { version=">=0.20.51.post4, <0.21", extras=["server-apps"] }
hypha-rpc = ">=0.20.53, <0.21"
redis = "==5.2.0"
async-retrying-ng = ">=0.1.3, <0.2"
