[workspace]
authors = ["Matthew McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
name = "cmake-w3-externaldata-upload"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"

[pypi-dependencies]
duckdb = ">=1.2.2, <2"
mailjet-rest = ">=1.4.0, <2"
python-dotenv = ">=1.1.0, <2"
retrying-async = ">=2.0.0, <3"
hypha = ">=0.20.51.post4, <0.21"
