[workspace]
authors = ["Matthew McCormick <matt@mmmccormick.com>"]
channels = ["conda-forge"]
name = "cmake-w3-externaldata-upload"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pnpm-install = { cmd="pnpm install", description="Install JavaScript dependencies", outputs=["node_modules/.pnpm-workspace-state.json"] }

[dependencies]
python = "3.13.*"
pnpm = ">=10.10.0,<11"

[pypi-dependencies]
duckdb = ">=1.2.2, <2"
mailjet-rest = ">=1.4.0, <2"
python-dotenv = ">=1.1.0, <2"
retrying-async = ">=2.0.0, <3"
hypha = { version=">=0.20.51.post4, <0.21", extras=["server-apps"] }
hypha-rpc = ">=0.20.53, <0.21"
redis = "==5.2.0"
